name: Release

on:
  push: {tags: ['v*']}

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          curl -1fsSLR https://github.com/curatorium/bash-import/releases/latest/download/bash-import -o /usr/local/bin/bash-import;
          chmod +x /usr/local/bin/bash-import;
          curl -1fsSLR https://github.com/curatorium/bash-import/releases/latest/download/bash-test -o /usr/local/bin/bash-test;
          chmod +x /usr/local/bin/bash-test;

      - name: Run checks (shellcheck + tests)
        run: .githooks/pre-commit

      - name: Build release artifacts
        run: bash-import pack bash-args.sh -o .dist/bash-args.sh

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "${{ github.ref_name }}" --title "${{ github.ref_name }}" --generate-notes --latest .dist/*
